version: "3.9"

networks:
  default:
    name: net-vuejs-bridge
    driver: bridge

  vuejs:
    container_name: vuejs-admin
    image: dotiendat1751998/vuejs-admin:1.1
    volumes:
      - '/data/InfoCMS/backend/cms-admin-web/logs:/usr/local/InfoCMS/was/logs'
    ports:
      - "8082:8080"
      - "80:80"
    restart: always
