apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: dotiendat1751998/vuejs-admin:latest
      ports:
        - containerPort: 3000
